LANG_EXTENSIONS = {
    "Assembly": ".asm",
    "Batchfile": ".bat",
    "C": ".c",
    "C++": ".cpp",
    "C#": ".cs",
    "Clojure": ".clj",
    "CMake": ".cmake",
    "COBOL": ".cbl",
    "CoffeeScript": ".coffee",
    "CSS": ".css",
    "CSV": ".csv",
    "Dart": ".dart",
    "DM": ".dm",
    "Dockerfile": ".dockerfile",
    "Elixir": ".ex",
    "Erlang": ".erl",
    "Fortran": ".for",
    "Go": ".go",
    "Groovy": ".gvy",
    "Haskell": ".hs",
    "HTML": ".html",
    "INI": ".ini",
    "Java": ".java",
    "JavaScript": ".js",
    "JSON": ".json",
    "Julia": ".jl",
    "Kotlin": ".kt",
    "Lisp": ".lsp",
    "Lua": ".lua",
    "Makefile": ".mak",
    "Markdown": ".md",
    "Matlab": ".mlx",
    "Objective-C": ".m",
    "OCaml": ".ml",
    "Pascal": ".pas",
    "Perl": ".pl",
    "PHP": ".php",
    "PowerShell": ".ps",
    "Prolog": ".pl",
    "Python": ".py",
    "R": ".r",
    "Ruby": ".c",
    "Rust": ".rs",
    "Scala": ".sc",
    "Shell": ".sh",
    "SQL": ".sql",
    "Swift": ".swift",
    "TeX": ".tex",
    "TOML": ".TOML",
    "TypeScript": ".ts",
    "Verilog": ".vlg",
    "Visual Basic": ".cls",
    "XML": ".xml",
    "YAML": ".yaml",
}

LIZARD_SUPPORTED_LANGUAGES = [
    "Fortran",
    "Go",
    "Kotlin",
    "Ruby",
    "C",
    "C++",
    "C#",
    "Python",
    "Lua",
    "PHP",
    "Objective-C",
    "JavaScript",
    "Solidity",
    "Rust",
    "Scala",
    "TypeScript",
    "Java",
    "TTCN-3",
]

